/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as InstagramCommentsRouteImport } from './routes/instagram-comments'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SendEmailRouteImport } from './routes/send-email'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TestAccountsRouteImport } from './routes/test-accounts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramCommentsRoute = InstagramCommentsRouteImport.update({
  id: '/instagram-comments',
  path: '/instagram-comments',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SendEmailRoute = SendEmailRouteImport.update({
  id: '/send-email',
  path: '/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAccountsRoute = TestAccountsRouteImport.update({
  id: '/test-accounts',
  path: '/test-accounts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/doctors': typeof DoctorsRoute
  '/instagram-comments': typeof InstagramCommentsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/send-email': typeof SendEmailRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/test-accounts': typeof TestAccountsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/doctors': typeof DoctorsRoute
  '/instagram-comments': typeof InstagramCommentsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/send-email': typeof SendEmailRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/test-accounts': typeof TestAccountsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/doctors': typeof DoctorsRoute
  '/instagram-comments': typeof InstagramCommentsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/send-email': typeof SendEmailRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/test-accounts': typeof TestAccountsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/bookings'
    | '/doctors'
    | '/instagram-comments'
    | '/knowledge'
    | '/login'
    | '/send-email'
    | '/services'
    | '/settings'
    | '/test-accounts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/bookings'
    | '/doctors'
    | '/instagram-comments'
    | '/knowledge'
    | '/login'
    | '/send-email'
    | '/services'
    | '/settings'
    | '/test-accounts'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/bookings'
    | '/doctors'
    | '/instagram-comments'
    | '/knowledge'
    | '/login'
    | '/send-email'
    | '/services'
    | '/settings'
    | '/test-accounts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BookingsRoute: typeof BookingsRoute
  DoctorsRoute: typeof DoctorsRoute
  InstagramCommentsRoute: typeof InstagramCommentsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  SendEmailRoute: typeof SendEmailRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  TestAccountsRoute: typeof TestAccountsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-comments': {
      id: '/instagram-comments'
      path: '/instagram-comments'
      fullPath: '/instagram-comments'
      preLoaderRoute: typeof InstagramCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-email': {
      id: '/send-email'
      path: '/send-email'
      fullPath: '/send-email'
      preLoaderRoute: typeof SendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-accounts': {
      id: '/test-accounts'
      path: '/test-accounts'
      fullPath: '/test-accounts'
      preLoaderRoute: typeof TestAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BookingsRoute: BookingsRoute,
  DoctorsRoute: DoctorsRoute,
  InstagramCommentsRoute: InstagramCommentsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  SendEmailRoute: SendEmailRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  TestAccountsRoute: TestAccountsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
